### ISSUE TITLE
Adding your translation to suttacentral.net

### ISSUE THREAD

**Issue by thesunshade** [zacanger/niddesa#7]
Hello!

Bhante Sujato has [expressed interest](https://discourse.suttacentral.net/t/an-english-translation-of-niddesa/23872/3?u=snowbird) in adding your translation to SuttaCentral. I understand that your license would allow this, but I'm wondering you are at as far as proofreading and updates. 

Thanks for your hard work on creating this.

**Comment by zautumnz** [comment]
I definitely want to work on an updated version, just haven't had the time (pull requests are always welcome!). I'm hoping to take a stab at it this summer.

(Also, @sujato, the line breaks in the HTML are generated by Pandoc — I would never even write much HTML by hand anymore!)

**Comment by thesunshade** [comment]
I'm wondering if you have had time to work on this or if you see yourself having time in the near future. Just checking in.

**Comment by zautumnz** [comment]
@thesunshade Yes! I've begun work on V2, partially based on [this corpus](https://github.com/x39826/Pali_Tripitaka) (I still don't actually know Pali!). I haven't pushed that work yet due to its size (don't want to bloat the repo or deal with filter-branch). Right now I think I'm on track to have V2 ready to go sometime in October (a season later than I originally expected).

**Comment by thesunshade** [comment]
Great to hear. Have you considered doing the translation using the Bilara software created for Sutta Central? That would allow the translation to be viewed (at the reader's discretion) side by side with the Pali. Any thoughts, Bhante @sujato?

**Comment by zautumnz** [comment]
I took a look at Bilara, but I'm very comfortable with my current workflow (Vimmers get set in their ways). I'd be happy to get the data into Bilara once V2 is ready though.

**Comment by thesunshade** [comment]
> I'd be happy to get the data into Bilara once V2 is ready though.

Wow, that would be great. The only special consideration with putting it into the Bilara system is that the SuttaCentral policy is that those translations are CC0/public domain.

If you wanted a different license, then it would need to be added as html files into the legacy system. I think Bhante Sujato would be happy to have it added either way.

**Comment by zautumnz** [comment]
Hey just a quick update, V2 is nearly finished. I have about 140 passages that still need to be fixed, but then it'll be good to go, so probably by Sunday after next at the latest. I've also switched to CC0 (on the V2 branch). I'll probably end up doing a third major revision sometime when life slows down a bit and I'm better recovered from Covid, but V2 will be usable enough for most folks.

**Comment by thesunshade** [comment]
Congratulations! And I wish you a speedy recovery.

Let me know what your interest is in putting the translation into Bilara.

**Comment by zautumnz** [comment]
Thanks. I think it would be valuable to have in Bilara, though I didn't retain line numbers everywhere, due to rewording some passages and omitting some longer repetitions within the same chapters. Looks like the schema Bilara uses probably requires line numbers to be the same across translations? In the mean time, I could absolutely get the text into regular SC. I'm guessing that would mean the sc-data repo? I'm poking through the wikis right now trying to figure out the format, since I'm currently just generating a single long file for each filetype.

**Comment by thesunshade** [comment]
> Looks like the schema Bilara uses probably requires line numbers to be the same across translations?

Yes. You can see in `bilara-data` how the translations are stored in json files with the keys being segment numbers. It's fine to have empty segments, though. This often happens with places with repetitions.

> I'm guessing that would mean the sc-data repo?

Yes. My understanding is that the actual format of the html file is not so strict. I'm not sure if the segment numbers are even required in these texts. The technical term for these translations is "legacy translations".

Do you have an account on the [SC discussion forum](https://discourse.suttacentral.net/)? I think that is usually how Bhante Sujato works with people on preparing translations.

**Comment by zautumnz** [comment]
I'm going to close this because the work presumably has been taken over by someone else in the EBT community. There are more details in the sutta-central Discourse thread, but for others' reference: the main blocker for me was that I don't have time to reformat the whole text to align with the Pali verses, because I did this translation from a Chinese version that didn't preserve those verses and lines.
